### ISSUE TITLE
Deserialization issue

### ISSUE THREAD

**Issue by mwexcell** [suvera/scim2-sdk#6]
It looks like this client library can't handle the standard response from Atlassian Guard. It includes a partial second in timestamp result fields:

Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Date` from String "2018-05-03T19:31:29.723Z": expected format "yyyy-MM-dd'T'hh:mm:ss'Z'"
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 36, column: 21] (through reference chain: dev.suvera.scim2.schema.data.sp.SpConfig["meta"]->dev.suvera.scim2.schema.data.meta.MetaRecord["lastModified"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)

Here is the relevant part of the enclosing stacktrace:

Got SCIM Implementation Details
2024-09-26 17:16:23,608 ERROR [dev.suvera.keycloak.scim2.storage.storage.ScimClient2] (executor-thread-9) Scim2ClientBuilder failed: dev.suvera.scim2.schema.ex.ScimException: Could not parse response for ServiceProviderConfig
	at dev.suvera.scim2.schema.util.Scim2Protocol.buildSpConfig(Scim2Protocol.java:90)
	at dev.suvera.scim2.schema.util.Scim2Protocol.<init>(Scim2Protocol.java:68)
	at dev.suvera.scim2.client.Scim2ClientImpl.init(Scim2ClientImpl.java:139)
	at dev.suvera.scim2.client.Scim2ClientImpl.<init>(Scim2ClientImpl.java:61)
	at dev.suvera.scim2.client.Scim2ClientBuilder.build(Scim2ClientBuilder.java:45)
	at dev.suvera.keycloak.scim2.storage.storage.ScimClient2.<init>(ScimClient2.java:86)
	at dev.suvera.keycloak.scim2.storage.storage.SkssStorageProviderFactory.validateConfiguration(SkssStorageProviderFactory.java:74)
	at org.keycloak.models.jpa.RealmAdapter.importComponentModel(RealmAdapter.java:2153)

Because of this, we can't save or use this provider in Keycloak w/ Atlassian.  Thoughts?

**Comment by suvera** [comment]
@mwexcell 
it should be fixed in 1.0.2 , please update the sdk version in the library. https://github.com/suvera/keycloak-scim2-storage/commit/45ff2d87ed80e8579f2353b969bc2d6f2dca7fe5

**Comment by mwexcell** [comment]
Rebuilt with the change, and that issue went away.  It does have a different one now, but I'll open a new issue for that. Thank you!!!!
